name: goreleaser

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    permissions:
        id-token: write
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_TO_TAP }}
      - name: Run GoReleaser to legacy tap
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .goreleaser-legacy-tap.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_TO_LEGACY_TAP }}
      - name: Run GoReleaser to turso-cli repo
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .goreleaser-self.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_TO_SELF }}
      - name: Get version
        id: get_version
        run: echo "VERSION={ \"Version\":\"$GITHUB_REF_NAME\"}" >> $GITHUB_OUTPUT
        shell: bash
      - name: Echo
        run: echo ${{ steps.get_version.outputs.VERSION }}
      - name: Update Turso backoffice
        uses: fjogeleit/http-request-action@v1
        with:
            url: 'https://api.turso.tech/releases'
            method: 'POST'
            data: ${{ steps.get_version.outputs.VERSION }}
            bearerToken: ${{ secrets.TURSOSTAFF_TOKEN }}
